<a href="https://colab.research.google.com/github/Althafvm/Data-science/blob/main/DATASCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
arr1=np.array([1,2,3])

arr2=np.array([3,2,4])

print(arr1+arr2)

print(arr1-arr2)

print(arr1*arr2)

print(arr1/arr2)

print(arr1**arr2)

print(arr1%arr2)

[4 4 7]
[-2  0 -1]
[ 3  4 12]
[0.33333333 1.         0.75      ]
[ 1  4 81]
[1 0 3]


In [ ]:
arr1=np.array([1,2,3])

arr2=np.array([3,2,4])

print(arr1>arr2)

print(arr1==arr2)

print(arr1!=arr2)

[False False False]
[False  True False]
[ True False  True]


In [ ]:
arr1=np.array([1,2,3])

arr2=np.array([[1,2,3],[5,4,6]])

arr3=np.array([[[1,2,3], [2,5,8], [7,8,9]]])

print(arr1.shape)

print(arr2.shape)

print(arr3.shape)

(3,)
(2, 3)
(1, 3, 3)


In [ ]:
arr1=np.array([1,2,3])

arr2=np.array([[1,2,3],[5,4,6]])

arr3=np.array([[[1,2,3], [2,5,8], [7,8,9]]])

arr4=np.array([[[[1,2,3],[2,5,7],[7,8,9],[8,9,10]]]])

arr5=np.array([[[[[1,2,3],[3,4,5],[5,6,7],[7,8,9],[9,10,11]]]]])

print(arr1.shape)

print(arr2.shape)

print(arr3.shape)

print(arr4.shape)

print(arr5.shape)

(3,)
(2, 3)
(1, 3, 3)
(1, 1, 4, 3)
(1, 1, 1, 5, 3)


In [ ]:
arr1=np.array([1,2,3])

arr2=np.array([3,2,4])

print(np.concatenate ((arr1,arr2)))

[1 2 3 3 2 4]


In [ ]:
elims=np.array([10,20,30,40,50])

print(elims[1:4])

[20 30 40]


In [ ]:
arr=np.zeros((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
